[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "xilophor"
name = "Disintegration"
description = "What's wrong with return false prefixes?"
websiteUrl = "https://github.com/Xilophor/Disintegration/"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../Disintegration/bin/Release/netstandard2.1/xilo.Disintegration.dll"
target = "/BepInEx/plugins/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "mods", "clientside" ]